# This file inspired by:
# https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139

dist: xenial

language: go

go:
  - 1.13.x

before_install:
  # Needed for test suite to pass
  - sudo apt-get install -y highlight

script:
  - ./test.sh
